<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    '12-hour' => 'Formato de 12 horas',
    '24-hour' => 'Formato de 24 horas',
    'Account Number' => 'Número de Cuenta',
    'Access denied.' => 'Acceso denegado.',
    'Address' => 'Dirección',
    'Article View' => 'Vista de Artículo',
    'Page View' => 'Vista de Página',
    '"{attribute}" must be a valid JSON' => '"{attribute}" debe de ser JSON válido',
    'Active' => 'Activo',
    'Article ID' => 'ID Artículo',
    'Author' => 'Autor',
    'Base URL' => 'URL Base',
    'Base Url' => 'Url Base',
    'Body' => 'Cuerpo',
    'Caption' => 'Leyenda',
    'Carousel ID' => 'Carrusel ID',
    'Category' => 'Categoría',
    'Client' => 'Cliente',
    'Comment' => 'Comentario',
    'Component' => 'Componente',
    'Config' => 'Configuración',
    'Country'=> 'País',
    'Created At' => 'Creado el',
    'Created at' => 'Creado el',
    'Day' => 'Día',
    'Deleted' => 'Borrado',
    'Down to maintenance.' => 'Apagado por mantenimiento.',
    'End of day' => 'Fin de jornada',
    'E-mail' => 'E-mail',
    'File Type' => 'Tipo fichero',
    'First day' => 'Primer día',
    'First day of week is Sunday'=> 'Primer día de la semana es el domingo',
    'First day of week language-dependant' => 'Primer día de la semana dependiendo del idioma',
    'First day of week is Monday' => 'Primer día de la semana es el lunes',
    'Firstname' => 'Nombre',
    'Hours format' => 'Formato de horas',
    'Gender' => 'Sexo',
    'ID' => 'ID',
    'Image' => 'Imagen',
    'Key' => 'Clave',
    'Last login' => 'Último Login',
    'Lastname' => 'Apellidos',
    'Locale' => 'Idioma',
    'Middlename' => 'Segundo Nombre',
    'Month' => 'Mes',
    'Name' => 'Nombre',
    'Number of Calendars' => 'Número de Calendarios',
    'Order' => 'Orden',
    'Parent Category' => 'Categoría Padre',
    'Path' => 'Ruta',
    'Phone' => 'Teléfono',
    'Picture' => 'Imagen',
    'Postal Code' => 'Código Postal',
    'Program' => 'Plan',
    'Province' => 'Provincia',
    'Published' => 'Publicado',
    'Published At' => 'Publicado el',
    'Size' => 'Tamaño',
    'Slug' => 'Slug',
    'Start Date' => 'Fecha de Alta',
    'Start day' => 'Inicio de jornada',
    'Status' => 'Estado',
    'Thumbnail' => 'Miniatura',
    'Time Interval' => 'Intervalo de tiempo',
    'Title' => 'Título',
    'Today' => 'Hoy',
    'Town' => 'Población',
    'Type' => 'Tipo',
    'Updated At' => 'Actualizado el',
    'Updated at' => 'Actualizado el',
    'Updater' => 'Actualizado por',
    'Upload Ip' => 'IP',
    'Url' => 'Url',
    'User ID' => 'Usuario ID',
    'Username' => 'Nombre Usuario',
    'Value' => 'Valor',
    'Week' => 'Semana',
    'Year' => 'Año',
];
